name: myenv
channels:
  - anaconda
  - defaults
dependencies:
  - autopep8=1.5.4=py_0
  - ca-certificates
  - certifi
  - django=3.1.2=py_0
  - krb5
  - libpq
  - openssl
  - pip
  - psycopg2
  - pycodestyle=2.6.0=py_0
  - python=3.8.5
  - pytz=2020.1=py_0
  - setuptools
  - sqlite
  - sqlparse=0.4.1=py_0
  - tk
  - toml=0.10.1=py_0
  # - vc
  # - vs2015_runtime
  - wheel=0.36.2=pyhd3eb1b0_0
  # - wincertstore
  - zlib
  - pip:
    - asgiref==3.2.10
    - dj-database-url==0.5.0
    - django-heroku==0.3.1
    - python-decouple==3.4
    - python-dotenv==0.15.0
    - whitenoise==5.2.0
    - openssl

    
# prefix: C:\Users\Arjun\anaconda3\envs\myenv
